### ISSUE TITLE
Incorrect error status code for Auth failure

### ISSUE THREAD

**Issue by v1tal3** [lykinsbd/naas#11]
If I submit a POST to send_command with no Authorization in the header, I get a 500 error returned.  This should return a 400-level error.

**Comment by lykinsbd** [comment]
I see where the issue is happening, in the `naas.library.decorators.valid_post()` decorator, I'm attempting to log the username _prior_ to validating that there was auth.  https://github.com/lykinsbd/naas/blob/master/naas/library/decorators.py#L35

And while I do have proper raising of `Unauthorized` in the actual `send_command`/`send_config` methods in the resources, we're never getting there and failing in the decorator.

I'll fix that logic around to be correct.
